# This is a basic workflow to help you get started with Actions

name: greeting_jobs

on:
  workflow_dispatch:

env: 
  DAY: Monday
  Name: Jonathanbarmousa

jobs:
   greeting_job:
    runs-on: ubuntu-latest
    env: 
      Greeting: Good Morning

    steps:
      - name: "Its Monday!"
        run: echo "$Greeting $Name!. Its $DAY!"

      - name: "I like mondays"
        run: echo "$Greeting, $Name you like $DAY"